config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root :to => "dashboard#index"

  match 'list_of_users', to: 'dashboard#list_of_users', via: [:get]
  match 'places_shared_by_you', to: 'dashboard#places_shared_by_you', via: [:get]
  match 'places_shared_with_you', to: 'dashboard#places_shared_with_you', via: [:get]
  match 'share_new_location', to: 'dashboard#share_new_location', via: [:get]
  match 'create_new_location', to: 'dashboard#create_new_location', via: [:post]

  get '/:username', to:'dashboard#display_public_places', as: "display_public_places"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"	

  geocoded_by :place
  after_validation :geocode
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sent_places, foreign_key: :sender_id, class_name: "Place"
  has_many :receivers, through: :sent_places


  has_many :received_places, foreign_key: :receiver_id, class_name: "Place"
  has_many :senders, through: :received_places       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if:  :devise_controller?


   
   protected

   def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
   end 

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index

  end	

  def list_of_users
    @users = User.all
  end

  def places_shared_by_you
    @places = current_user.sent_places.select('distinct place, longitude, latitude').where.not({ longitude: nil, latitude: nil })
    @places_coordinates = @places.pluck('longitude', 'latitude')
    @title = "Places shared by you"
  end	

  def places_shared_with_you 
    @places = current_user.received_places.select('distinct place, longitude, latitude').where.not({ longitude: nil, latitude: nil })
    @places_coordinates = @places.pluck('longitude', 'latitude')
    @title = "Places shared with you by others"
  end

  def display_public_places
  	user = User.find_by_username(params[:username])
    @places = user.sent_places.select('distinct place, longitude, latitude').where(is_public: true).where.not({ longitude: nil, latitude: nil })
    @places_coordinates = @places.pluck('longitude', 'latitude')
    @title = "Places shared publicly by #{user.username}"
  end	

  def share_new_location
  	@users = User.where.not(id: current_user.id).all 	
  end	

  def create_new_location
    if params[:public] == "1"
     params.delete "selected_users" 

     user_ids = User.where.not(id: current_user.id).pluck(:id)
     user_ids.each do |receiver_id|
      Place.create(:sender_id => current_user.id, :receiver_id => receiver_id, :place => params["place"], :is_public => true)
     end 
    else
     params["selected_users"].each do |receiver_id| 
      Place.create(:sender_id => current_user.id, :receiver_id => receiver_id, :place => params["place"], :is_public => false)
     end 
    end
    
    flash[:notice] = "Location shared successfully!"
    redirect_to places_shared_by_you_path
  end	
  	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_display_map.html.erb
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/css/ol.css">
    <style>
      .map {
        height: 400px;
        width: 100%;
      }
    </style>
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/build/ol.js"></script>

  </head>
  <body>
    <h2><%= @title %></h2>
    <div id="map" class="map"></div>
    <script type="text/javascript">

      var places_coordinates = new Array();
      places_coordinates = <%= @places_coordinates %>;
      
      const features = [];
      for (i = 0; i < places_coordinates.length; i++) {
        features.push(new ol.Feature({
          geometry: new ol.geom.Point(ol.proj.fromLonLat([
            places_coordinates[i][0], places_coordinates[i][1]
          ]))
        }));
      }

      const vectorSource = new ol.source.Vector({
        features
      });
      const vectorLayer = new ol.layer.Vector({
        source: vectorSource,
        style: new ol.style.Style({
          image: new ol.style.Circle({
            radius: 2,
            fill: new ol.style.Fill({color: 'red'})
          })
        })
      });

      const map = new ol.Map({
        target: 'map',
        layers: [
          new ol.layer.Tile({
            source: new ol.source.OSM()
          }),
          vectorLayer
        ],
        view: new ol.View({
          center: ol.proj.fromLonLat([-75, 35]),
          zoom: 2
        })
      });
    </script>

    <br />

     <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Place</th>
          <th scope="col">Longitude</th>
          <th scope="col">Latitude</th>
        </tr>
      </thead>
      <tbody>
       <% @places.each do |place| %> 
        <tr>
          <td><%= place.place %></td>
          <td><%= place.longitude %></td>
          <td><%= place.latitude %></td>
        </tr>
       <% end %>    
      </tbody>
     </table>

  </body>
</html>

app/views/dashboard/_header_navbar.html.erb
<style type="text/css">
  .bg-new {
    background-color: Wheat !important;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-new">
  <h2>PlaceShare</h2>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>

     <% if user_signed_in? %> 
      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Select an option
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/list_of_users">View list of all users</a>
          <a class="dropdown-item" href="/places_shared_by_you">Places shared by you</a>
          <a class="dropdown-item" href="/places_shared_with_you">Places shared with you</a>
          <a class="dropdown-item" href="/share_new_location">Share new location</a>
        </div>
      </li>
     <% end %> 
    </ul>
    

         <div id="user_nav">
           <% if user_signed_in? %>
                <div class="btn-group">
                  <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= current_user.email %>
                  </button>
                  <div class="dropdown-menu">  
                      <%= link_to 'Sign out', destroy_user_session_path, :class => "dropdown-item" %>
                  </div>
                </div>
            <% else %>
                <%= link_to 'Sign Up', new_user_registration_path, :class => "btn btn-outline-success my-2 my-sm-0" %> <%= link_to 'Log in', new_user_session_path, :class => "btn btn-outline-success my-2 my-sm-0" %>
            <% end %>
          </div>

  </div>
</nav>

app/views/dashboard/display_public_places.html.erb
Text

app/views/dashboard/index.html.erb
<% if user_signed_in? %>
  <h4>This is the Homepage. Select one the options in the dropdown above to continue</h4>
<% else %>
   <h4>Please Sign Up/ Log In to proceed</h4>
<% end %>

app/views/dashboard/list_of_users.html.erb
<h2>List of all users</h2>
<p>Click on one of the usernames to see their public shared location map</p>
<div class="container-fluid">
	
 <table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Email</th>
      <th scope="col">Username</th>
      <th scope="col">Signed up on</th>
    </tr>
  </thead>
  <tbody>
   <% @users.each do |user| %> 
    <tr>
      <td><%= user.email %></td>
      <td><%= link_to user.username, display_public_places_path(user.username) %></td>
      <td><%= user.created_at.strftime("%b %d, %Y") %></td>
    </tr>
   <% end %>    
  </tbody>
 </table>
</div>

app/views/dashboard/places_shared_by_you.html.erb
<%= flash[:notice] unless flash[:notice].blank? %>
<%= render "dashboard/display_map", :locals => {:places => @places} %>

app/views/dashboard/places_shared_with_you.html.erb
<%= render "dashboard/display_map", :locals => {:places => @places} %>

app/views/dashboard/share_new_location.html.erb
<h2>Share your location</h2>

<%= form_tag "/create_new_location", :id => "share_loc_form" do %>
  
  <div class="form-group">
    <p>Enter a Place (City/ Landmark) :</p> 
    <p> Ex: New York, Eiffel Tower, Taj Mahal etc. </p>
    <%= text_field_tag :place, '', :required => true %>
  </div>

  <div class="form-group">
    Share as public:
  	<%= check_box_tag "public" %>
  </div>

  

  <div class="form-group" id="users_select">
  <p>Or</p>
  Select users to share with:<br />

  	<%= select_tag 'selected_users', options_from_collection_for_select(@users, 'id', 'username'), { :multiple => true } %>
  </div>

  <div class="actions">
    <%= submit_tag "Submit" %>
  </div>

<% end %>

<script type="text/javascript">
  $('#public').mousedown(function() {
    if (!$(this).is(':checked')) {
    	$('#users_select').hide();
    }
    else
    {
    	$('#users_select').show();
    }	
   });

</script

app/views/layouts/_header_navbar.html.erb
<style type="text/css">
  .bg-new {
    background-color: Wheat !important;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-new">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<br/> <br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlaceSharingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/css/ol.css" type="text/css">
       

    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/build/ol.js"></script>    

  </head>

  <body>
    <div><%= render "dashboard/header_navbar" %></div><br />
    <div class="container"> 
     <%= yield %>
    </div> 
  </body>
</html>